# for use with openshift only
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipelines-vote-ui
  name: pipelines-vote-ui
  namespace: pipelines-tutorial
  #namespace: vote-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pipelines-vote-ui
  template:
    metadata:
      labels:
        app: pipelines-vote-ui
        date: 08-01-2025
        foo: gitops
    spec:
      containers:
        #- image: quay.io/openshift-pipeline/vote-ui:latest
        - image: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/pipelines-vote-ui
          imagePullPolicy: Always
          name: pipelines-vote-ui
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          env:
            - name: VOTING_API_SERVICE_HOST
              value: pipelines-vote-api
            - name: VOTING_API_SERVICE_PORT
              value: "9000"
