resources:
  - ../../base

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: vote-example-ingress
      namespace: vote-example
    path: ingress-patch.json

